#ifndef SOCIALBUTTERFLY_PACKETTYPE_H
#define SOCIALBUTTERFLY_PACKETTYPE_H

enum PacketType
{
    NUMERIC,
    FLOATING_POINT,
    SINGLE_CHAR,
    FIXED_STRING,
    VARIABLE_STRING
};

#endif //SOCIALBUTTERFLY_PACKETTYPE_H
